export const buildings = [
  //'Archery.FBX',
  'Archery.glb',
  //   'Barracks.FBX',
  //   'Blacksmith.FBX',
  //   'Castle.FBX',
  //   'Farm.FBX',
  //   'Granary.FBX',
  //   'House.FBX',
  //   'Keep.FBX',
  //   'Library.FBX',
  //   'LumberMill.FBX',
  //   'MageTower.FBX',
  //   'Market.FBX',
  //   'Stables.FBX',
  //   'Temple.FBX',
  //   'Tower_A.FBX',
  //   'Tower_B.FBX',
  //   'Tower_C.FBX',
  //   'TownHall.FBX',
  //   'Wall_A_1x1.FBX',
  //   'Wall_A_corner.FBX',
  //   'Wall_A_gate.FBX',
  //   'Wall_A_wall.FBX',
  //   'Wall_B_1x1.FBX',
  //   'Wall_B_corner.FBX',
  //   'Wall_B_gate.FBX',
  //   'Wall_B_wall.FBX',
  //   'Workshop.FBX',
];
