///Applications/Blender.app/Contents/MacOS/Blender --background --python-expr "import bpy; bpy.ops.import_scene.fbx(filepath='/Users/x86/repos/u-p3/Assets/ToonyTinyPeople/TT_RTS/TT_RTS_Standard/models/buildings/Archery.FBX'); bpy.ops.export_scene.fbx(filepath='/Users/x86/repos/gd-2d-shooter/assets/TT_RTS_Standard/models/output.fbx', use_selection=False, axis_forward='-Z', axis_up='Y')"
export const buildings = [
  'TownHall.FBX',
  'Barracks.FBX',
  'Blacksmith.FBX',
  'Castle.FBX',
  'Farm.FBX',
  'Granary.FBX',
  'House.FBX',
  'Keep.FBX',
  'Library.FBX',
  'LumberMill.FBX',
  'MageTower.FBX',
  'Market.FBX',
  'Stables.FBX',
  'Temple.FBX',
  'Tower_A.FBX',
  'Tower_B.FBX',
  'Tower_C.FBX',
  'TownHall.FBX',
  'Wall_A_1x1.FBX',
  'Wall_A_corner.FBX',
  'Wall_A_gate.FBX',
  'Wall_A_wall.FBX',
  'Wall_B_1x1.FBX',
  'Wall_B_corner.FBX',
  'Wall_B_gate.FBX',
  'Wall_B_wall.FBX',
  'Workshop.FBX',
];

export const units = ['TT_RTS_Cavalry_customizable.FBX', 'TT_RTS_Characters_customizable.FBX', 'TT_RTS_Ballista.FBX', 'TT_RTS_Cart.FBX', 'TT_RTS_Catapult.FBX', 'TT_RTS_Ram.FBX'];
